version: '3.1'
services:
  db:
    image: mysql
    container_name: consultafrete_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./src/main/resources/calculafrete_data:/var/lib/mysql

volumes:
  gean_data: