server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calculafrete?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

frete:
  parametros-desconto:
    ddd:
      desconto: 0.5
      dias: 1
    uf:
      desconto: 0.75
      dias: 3
refpath:
  swagger:
    path: localhost:8080
    apiinfo:
      title: "Calculo de Frete SigaBem API"
      description: "Desafio de Calculo api"
      termsOfServiceUrl: "http://localhost:8080"
      license: ""
      licenseUrl: "http://localhost:8080"
      version: "1.0"
